version: "3.8"
services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mariadb:/var/lib/mysql

  web: &web
    build: .
    image: rails_app:1.0.0
    volumes:
      - .:/app:cached
      - bundle:/app/vendor/bundle
    environment:
      BUNDLE_PATH: "/app/vendor/bundle"
      RAILS_MASTER_KEY:
    depends_on:
      - db
    command: ["rails", "server", "-b", "0.0.0.0"]
    expose: ["3000"]
    ports: ["3000:3000"]

volumes:
  mariadb:
  bundle:
